services:
  arkive:
    container_name: arkive
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${EXTERNAL_PORT:-8082}:${SERVER_PORT:-8082}"
    volumes:
      - ./data:/app/data
    environment:
      - SESSION_SECRET=${SESSION_SECRET}
    env_file:
      - .env
    restart: unless-stopped